const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Plugins.Touch,
		C3.Plugins.gamepad,
		C3.Behaviors.Bullet,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.AngleWithin,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.Shape3D.Acts.SetX,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Shape3D.Acts.AddChild,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.System.Acts.SubVar
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{Tween: 0},
	{PlayerBillboard: 0},
	{Ground: 0},
	{Keyboard: 0},
	{Skybox: 0},
	{GroundSpawnPoint: 0},
	{SkyTexture: 0},
	{Clouds: 0},
	{Spike: 0},
	{PlayerCollision: 0},
	{Plant: 0},
	{Zeppelin: 0},
	{GroundTexture: 0},
	{PlayerAnimations: 0},
	{Pillar: 0},
	{"3DShape": 0},
	{"3DShape2": 0},
	{"3DShape3": 0},
	{Touch: 0},
	{Gamepad: 0},
	{Bullet: 0},
	{Dust: 0},
	{Tutorial: 0},
	{TitleText: 0},
	{MipIcon: 0},
	{Instruct: 0},
	{Audio: 0},
	{kaboom: 0},
	{black: 0},
	{deertext: 0},
	{racerIcon: 0},
	{Browser: 0},
	{InitialX: 0},
	{InitialY: 0},
	{AllowMovement: 0},
	{AngleOfMotion: 0},
	{Direction: 0},
	{GroundSpeed: 0},
	{TILESIZE: 0},
	{MINDISTANCE: 0},
	{MINTILES: 0},
	{MAXTILES: 0},
	{MINLENGTH: 0},
	{MAXLENGTH: 0},
	{Score: 0},
	{randomfun: 0},
	{Racer: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	PlayerBillboard: class extends self.I3DShapeInstance {},
	Ground: class extends self.I3DShapeInstance {},
	Keyboard: class extends self.IInstance {},
	Skybox: class extends self.I3DShapeInstance {},
	GroundSpawnPoint: class extends self.ISpriteInstance {},
	SkyTexture: class extends self.ITiledBackgroundInstance {},
	Clouds: class extends self.ITiledBackgroundInstance {},
	Spike: class extends self.I3DShapeInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	Plant: class extends self.I3DShapeInstance {},
	Zeppelin: class extends self.I3DShapeInstance {},
	GroundTexture: class extends self.IWorldInstance {},
	PlayerAnimations: class extends self.ISpriteInstance {},
	Pillar: class extends self.I3DShapeInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	_3DShape2: class extends self.I3DShapeInstance {},
	_3DShape3: class extends self.I3DShapeInstance {},
	Touch: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Dust: class extends self.I3DShapeInstance {},
	Tutorial: class extends self.ISpriteFontInstance {},
	TitleText: class extends self.ISpriteFontInstance {},
	MipIcon: class extends self.ISpriteInstance {},
	Instruct: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	kaboom: class extends self.ISpriteInstance {},
	black: class extends self.ISpriteInstance {},
	deertext: class extends self.ISpriteFontInstance {},
	racerIcon: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {}
}